### ISSUE TITLE
Question about ${NPM_TOKEN}`

### ISSUE THREAD

**Issue by Netyson** [TheSPSDAO/SPS-Validator#1]
I noticed that the [https://github.com/TheSPSDAO/dev-hive-container](https://github.com/TheSPSDAO/dev-hive-container) repository is still empty—maybe this could be updated soon.

Also, in the `.env` files, it seems like the `NPM_TOKEN` is required. I assume the validator is using some custom Node packages that are only accessible to the team. Will these packages eventually be made public, or are they specific to the internal team?

without it you cant run the dockerfile:
` NPM_TOKEN: ${NPM_TOKEN:-}`  
 `npm.pkg.github.com/:_authToken=${NPM_TOKEN}`  
`@steem-monsters:registry=https://npm.pkg.github.com/`

**Comment by smoyer-sl** [comment]
The npm package that token is for is already public, https://github.com/steem-monsters/atom/pkgs/npm/atom. I don't think you need it.

We are in the middle of updating the docker setup process, but for now you can try removing these two lines (leave the registry one though),
```
NPM_TOKEN: ${NPM_TOKEN:-} # remove from the docker files
npm.pkg.github.com/:_authToken=${NPM_TOKEN} # remove from the npmrc
```

Let me know if that works.
